version: 2.1
executors:
  exectr:
    docker:
      - image: andykirkham/dockerfilerepositoryforcpp
jobs:
  build:
    executor: exectr
    working_directory: /tmp
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            mkdir build
            cd build
            cmake ..
            make
      - persist_to_workspace:
          root: .
          paths: build
  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd build
            ctest --verbose
      - store_test_results:
          path: build
      - run:
        name: Creating Artifacts
        command: |
          echo "libcsgp4.a" > /tmp/art-1;
          mkdir /tmp/artifacts;
          echo "my artifact files in a dir" > /tmp/artifacts/art-2;
    - store_artifacts:
        path: /tmp/art-1
        destination: libcsgp4.a
    - store_artifacts:
        path: /tmp/artifacts
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
            

version: 2
jobs:
build:
  working_directory: /tmp
  steps:
    - run:
        name: Creating Dummy Artifacts
        command: |
          echo "my artifact file" > /tmp/art-1;
          mkdir /tmp/artifacts;
          echo "my artifact files in a dir" > /tmp/artifacts/art-2;

    - store_artifacts:
        path: /tmp/art-1
        destination: artifact-file

    - store_artifacts:
        path: /tmp/artifacts
            