version: 2.1
jobs:
  build:
    docker:
      - image: andykirkham/dockerfilerepositoryforcpp:latest
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            mkdir build
            cd build
            cmake ..
            make
      - persist_to_workspace:
          root: .
          path: build
  test:
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Execute Tests
          command: |
            cd build
            ctest --verbose --output-junit unittestresults.xml
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
